import { Suspense } from "react";
import Link from "next/link";
import { notFound } from "next/navigation";

import {
  ApproveBriefButton,
  DiscoveryComposer,
  MoveToDefineButton,
} from "@/components/discovery/composer";
import { BriefPanel } from "@/components/discovery/brief-panel";
import { StartDiscoveryForm } from "@/components/discovery/start-form";
import { PageSkeleton } from "@/components/feedback/states";
import {
  CLARITY_AREAS,
  DISCOVERY_STATUS_LABEL,
  PRODUCT_BRIEF_STATUS_LABEL,
  SIGNAL_LEVEL_LABEL,
  STAGE_META,
} from "@/domain/constants";
import { formatDateTime } from "@/lib/format";
import { NextActionPanel } from "@/components/guidance/guidance-ui";
import { readinessSummary } from "@/modules/discovery/merge";
import { getProductGuidance } from "@/modules/guidance/service";
import { getDiscoveryWorkspace } from "@/modules/discovery/service";
import { markDynamic } from "@/server/dynamic";

export const metadata = { title: "Discovery" };
export const maxDuration = 60;

const ROLE_LABEL = {
  USER: "You",
  ASSISTANT: "Discovery lead",
  SYSTEM: "Session",
} as const;

export default function DiscoveryPage({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ version?: string }>;
}) {
  return (
    <Suspense fallback={<PageSkeleton />}>
      <Discovery params={params} searchParams={searchParams} />
    </Suspense>
  );
}

async function Discovery({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ version?: string }>;
}) {
  await markDynamic();
  const { id } = await params;
  const query = await searchParams;
  const version = Number(query.version);
  const [workspace, guidance] = await Promise.all([
    getDiscoveryWorkspace(id, Number.isFinite(version) && version > 0 ? version : undefined),
    getProductGuidance(id),
  ]);
  if (!workspace || !guidance) notFound();

  const { product, session, brief, configured } = workspace;

  return (
    <div className="space-y-5">
      <header className="rounded-2xl border bg-card p-4 sm:p-5">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <p className="text-xs font-medium tracking-[0.14em] text-muted-foreground uppercase">
              Explore
            </p>
            <h2 className="mt-1 text-xl font-semibold">Product discovery</h2>
            <p className="mt-1 max-w-2xl text-sm leading-6 text-muted-foreground">
              Do we understand the problem well enough to define the product? The brief stays a proposal until a person approves it.
            </p>
          </div>
          <span className="w-fit rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-medium text-indigo-800">
            {session ? DISCOVERY_STATUS_LABEL[session.status] : "Not started"}
          </span>
        </div>
        {brief ? (
          <details className="mt-5">
            <summary className="cursor-pointer text-sm font-medium">How the brief was judged</summary>
            <p className="mt-2 text-sm">{readinessSummary(workspace.sufficientAreas)}</p>
            <p className="mt-1 text-xs text-muted-foreground">These notes are not a completion percentage.</p>
            <dl className="mt-3 grid gap-2 sm:grid-cols-5">
              {CLARITY_AREAS.map((area) => {
                const level = brief[area.key];
                return (
                  <div key={area.key} className="rounded-xl border bg-background px-3 py-2">
                    <dt className="text-[11px] text-muted-foreground">{area.label}</dt>
                    <dd className="mt-1 text-xs font-medium">{SIGNAL_LEVEL_LABEL[level]}</dd>
                  </div>
                );
              })}
            </dl>
          </details>
        ) : null}
      </header>
      {guidance.stage === "EXPLORE" ? <NextActionPanel guidance={guidance} /> : null}

      {!configured ? (
        <p className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm leading-6 text-amber-950">
          AI is not configured. Set OPENAI_API_KEY on the server to run Product Discovery. The application stays available, and no model response is invented.
        </p>
      ) : null}
      {session?.seededDemo ? (
        <p className="rounded-2xl border bg-stone-50 px-4 py-3 text-sm leading-6 text-stone-700">
          Demo data. This discovery session was prepared so the Claims Management Platform workspace can be reviewed. It was not generated by a live model. Proposed sections are sample content, not confirmed fact.
        </p>
      ) : null}
      {session?.status === "READY_FOR_REVIEW" && !workspace.viewingHistorical ? (
        <div className="rounded-2xl border border-indigo-200 bg-indigo-50 px-4 py-4">
          <h3 className="font-semibold text-indigo-950">Discovery Ready for Review</h3>
          <p className="mt-1 text-sm leading-6 text-indigo-950/80">
            {brief?.readinessReason || "The discovery lead believes there is enough to review. This is not approval."}
          </p>
          <div className="mt-3">
            <ApproveBriefButton productId={product.id} />
          </div>
        </div>
      ) : null}
      {session?.status === "APPROVED" ? (
        <div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-4">
          <h3 className="font-semibold text-emerald-950">
            Discovery approved. Product is ready to move to Define.
          </h3>
          <p className="mt-1 text-sm leading-6 text-emerald-950/80">
            Approval did not change the product stage. Only a person can move Explore to Define.
          </p>
          <div className="mt-3">
            {product.currentStage === "EXPLORE" ? (
              <MoveToDefineButton productId={product.id} />
            ) : (
              <p className="text-sm text-emerald-950">
                This product is already in {STAGE_META[product.currentStage].label}. Discovery will not move it backward.
              </p>
            )}
          </div>
        </div>
      ) : null}
      {workspace.latestError ? (
        <p className="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm leading-6 text-rose-900">
          The last discovery turn failed. {workspace.latestError} The product brief was left unchanged.
        </p>
      ) : null}

      {!session || !brief ? (
        <section className="rounded-2xl border bg-card p-5 sm:p-6">
          <h3 className="text-lg font-semibold">Start Product Discovery</h3>
          <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">
            Turn an initial product idea into a validated Product Brief before moving into detailed requirements and delivery planning.
          </p>
          <div className="mt-5">
            <StartDiscoveryForm productId={product.id} />
          </div>
        </section>
      ) : (
        <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1.15fr)_minmax(320px,0.85fr)]">
          <section className="rounded-2xl border bg-card p-4 sm:p-5">
            <div className="flex items-center justify-between gap-3">
              <h3 className="text-sm font-semibold">Discovery conversation</h3>
              <p className="text-xs text-muted-foreground">
                {workspace.messages.length} notes
              </p>
            </div>
            <ol className="mt-4 max-h-[42rem] space-y-4 overflow-y-auto pr-1">
              {workspace.messages.map((message) => (
                <li
                  key={message.id}
                  className={
                    message.role === "ASSISTANT"
                      ? "rounded-xl border border-indigo-100 bg-indigo-50/60 p-3"
                      : message.role === "SYSTEM"
                        ? "rounded-xl bg-stone-50 p-3"
                        : "rounded-xl border bg-background p-3"
                  }
                >
                  <div className="flex items-center justify-between gap-3">
                    <p className="text-xs font-semibold tracking-wide uppercase">
                      {ROLE_LABEL[message.role]}
                    </p>
                    <time className="text-[11px] text-muted-foreground" dateTime={message.createdAt.toISOString()}>
                      {formatDateTime(message.createdAt)}
                    </time>
                  </div>
                  <p className="mt-2 text-sm leading-6 whitespace-pre-wrap">{message.content}</p>
                </li>
              ))}
            </ol>
            {workspace.viewingHistorical ? (
              <p className="mt-4 text-sm text-muted-foreground">
                You are reading an earlier brief version. The panel on the right is read only. Replies update the current version.
              </p>
            ) : null}
            <DiscoveryComposer
              productId={product.id}
              configured={configured}
              canRetry={workspace.canRetry}
              approved={session.status === "APPROVED"}
              canApprove={session.status === "IN_PROGRESS" && !workspace.viewingHistorical}
            />
            <History
              productId={product.id}
              versions={workspace.versions}
              currentVersion={brief.version}
              approvals={workspace.approvals}
            />
          </section>
          <BriefPanel
            productId={product.id}
            brief={brief}
            editable={!workspace.viewingHistorical}
          />
        </div>
      )}
    </div>
  );
}

function History({
  productId,
  versions,
  currentVersion,
  approvals,
}: {
  productId: string;
  versions: { id: string; version: number; status: keyof typeof PRODUCT_BRIEF_STATUS_LABEL; createdAt: Date }[];
  currentVersion: number;
  approvals: { id: string; status: string; approvedBy: string | null; comments: string; resolvedAt: Date | null }[];
}) {
  return (
    <div className="mt-6 space-y-4 border-t pt-4">
      <div>
        <h3 className="text-sm font-semibold">Brief versions</h3>
        <ul className="mt-2 flex flex-wrap gap-2">
          {versions.map((version) => (
            <li key={version.id}>
              <Link
                href={
                  version.version === versions[0]?.version
                    ? `/products/${productId}/discovery`
                    : `/products/${productId}/discovery?version=${version.version}`
                }
                className={
                  version.version === currentVersion
                    ? "inline-flex rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-medium text-indigo-800"
                    : "inline-flex rounded-full bg-stone-100 px-2.5 py-1 text-xs text-stone-700"
                }
              >
                v{version.version} · {PRODUCT_BRIEF_STATUS_LABEL[version.status]}
              </Link>
            </li>
          ))}
        </ul>
      </div>
      <div>
        <h3 className="text-sm font-semibold">Discovery approvals</h3>
        {approvals.length === 0 ? (
          <p className="mt-1 text-sm text-muted-foreground">No discovery approval yet.</p>
        ) : (
          <ul className="mt-2 space-y-2">
            {approvals.map((approval) => (
              <li key={approval.id} className="text-sm leading-6">
                <span className="font-medium">{approval.status}</span>
                {approval.approvedBy ? ` by ${approval.approvedBy}` : ""}
                {approval.resolvedAt ? ` · ${formatDateTime(approval.resolvedAt)}` : ""}
                {approval.comments ? ` — ${approval.comments}` : ""}
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
