import type { ArchitectureResponse } from "@/modules/architecture/schema";

export function architectureFixture(refs: {
  nfrId: string;
  capabilityId: string;
  storyId: string;
}): ArchitectureResponse {
  return {
    assistantSummary:
      "A modular monolith can take a straightforward claim from the customer screen to a stored notice.",
    systemKind: "GREENFIELD",
    architectureStyle: "Modular monolith",
    architectureSummary:
      "One application holds the claim submission flow. The customer screen calls a claims API, which uses a claims service and a claims database.",
    rationale:
      "The first slice is one journey. A modular monolith satisfies it without operating several deployable services.",
    frontendApproach: "A small customer web application for the notice form and confirmation.",
    backendApproach: "A claims API and a claims service inside the same application.",
    dataApproach: "A claims record owned by the claims service, stored in PostgreSQL.",
    integrationApproach: "No external integration is required for the first slice beyond an identity provider assumption.",
    securityApproach: "The customer sees only the notice they submitted. Authentication is still an open question.",
    deploymentApproach: "One application deployment for the first slice.",
    observabilityApproach: "Log claim submission success and failure with the claim reference.",
    components: [
      {
        tempId: "component-1",
        name: "Customer Web Application",
        type: "USER_INTERFACE",
        description: "The customer enters a straightforward claim and sees the confirmation.",
        responsibilities: "Collect the notice and show the claim reference.",
        technology: "Web application",
        rationale: "The slice is a customer journey.",
        capabilityIds: [refs.capabilityId],
        workItemIds: [refs.storyId],
        nfrIds: [refs.nfrId],
      },
      {
        tempId: "component-2",
        name: "Claims API",
        type: "API",
        description: "Application boundary for submitting a claim.",
        responsibilities: "Accept a valid notice and return a claim reference.",
        technology: "HTTP API",
        rationale: "The screen needs a stable boundary.",
        capabilityIds: [refs.capabilityId],
        workItemIds: [refs.storyId],
        nfrIds: [],
      },
      {
        tempId: "component-3",
        name: "Claims Service",
        type: "SERVICE",
        description: "Creates the claim and keeps the submission rules.",
        responsibilities: "Validate the notice and store it.",
        technology: "Application service",
        rationale: "Rules should not live only in the screen.",
        capabilityIds: [refs.capabilityId],
        workItemIds: [refs.storyId],
        nfrIds: [],
      },
      {
        tempId: "component-4",
        name: "Claims Database",
        type: "DATABASE",
        description: "Stores the claim notice.",
        responsibilities: "Persist the claim and its reference.",
        technology: "PostgreSQL",
        rationale: "The product already uses a relational store for structured notices.",
        capabilityIds: [],
        workItemIds: [],
        nfrIds: [],
      },
    ],
    relationships: [
      {
        tempId: "relationship-1",
        sourceTempId: "component-1",
        targetTempId: "component-2",
        relationshipType: "CALLS",
        description: "The screen submits the notice.",
      },
      {
        tempId: "relationship-2",
        sourceTempId: "component-2",
        targetTempId: "component-3",
        relationshipType: "CALLS",
        description: "The API delegates to the claims service.",
      },
      {
        tempId: "relationship-3",
        sourceTempId: "component-3",
        targetTempId: "component-4",
        relationshipType: "WRITES_TO",
        description: "The service stores the claim.",
      },
    ],
    technologyDecisions: [
      {
        tempId: "technology-1",
        choice: "PostgreSQL",
        reason: "The notice is structured and the factory already runs on PostgreSQL.",
        alternatives: "A document store was considered and adds a second operational model.",
        tradeoffs: "Relational constraints help the first slice and can limit unusual payloads.",
        relevantConstraint: "Keep the first slice operable by a small team.",
      },
    ],
    adrs: [
      {
        tempId: "adr-1",
        title: "Use a modular monolith for the first claim slice",
        context: "The approved slice is one customer journey.",
        decision: "Keep the API, service, and customer screen in one deployable application.",
        rationale: "Complexity must stay inside one codebase until the slice proves the journey.",
        alternatives: "Separate deployable services for the API and the screen.",
        consequences: "A later split remains possible at the service boundary.",
      },
    ],
    dataDesign: [
      {
        tempId: "data-1",
        name: "Claim",
        description: "The straightforward notice and its confirmation reference.",
        owner: "Claims service",
        classification: "CONFIDENTIAL",
        retention: "Retention period is not confirmed.",
        relationships: "A claim belongs to one customer contact method.",
        externalSource: "",
      },
    ],
    integrations: [
      {
        tempId: "integration-1",
        name: "Identity provider",
        purpose: "Establish who is submitting the notice once the provider is chosen.",
        direction: "OUTBOUND",
        protocol: "OIDC",
        authenticationAssumption: "The provider is not chosen yet.",
        dataExchanged: "A subject identifier and the policy number the customer entered.",
        failureConsiderations: "If identity is unavailable, submission does not proceed.",
      },
    ],
    securityAssessment: [
      {
        tempId: "finding-1",
        area: "AUTHENTICATION",
        classification: "DECISION_REQUIRED",
        title: "The identity provider is not chosen",
        description: "Initial Architecture Security Assessment. Submission should not guess an identity system.",
      },
      {
        tempId: "finding-2",
        area: "AUTHORISATION",
        classification: "CONCERN",
        title: "A customer must not see another customer's notice",
        description: "The API must scope every read and write to the authenticated customer.",
      },
      {
        tempId: "finding-3",
        area: "SENSITIVE_DATA",
        classification: "INFORMATION",
        title: "Policy numbers and contact details are sensitive",
        description: "Treat the notice as confidential customer data.",
      },
      {
        tempId: "finding-4",
        area: "ENCRYPTION",
        classification: "INFORMATION",
        title: "Protect the notice in transit and at rest",
        description: "Use the platform transport and database encryption already available.",
      },
      {
        tempId: "finding-5",
        area: "SECRETS",
        classification: "INFORMATION",
        title: "Keep connection details out of the client",
        description: "The customer screen does not receive database credentials.",
      },
      {
        tempId: "finding-6",
        area: "AUDITABILITY",
        classification: "INFORMATION",
        title: "Record that a notice was submitted",
        description: "Write an audit event with the claim reference and the time.",
      },
    ],
    nfrCoverage: [
      {
        tempId: "coverage-1",
        nfrId: refs.nfrId,
        componentTempId: "component-1",
        adrTempId: "adr-1",
        mechanism: "The customer screen and the API scope the notice to the submitting customer.",
      },
    ],
    architectureQuestions: [
      {
        tempId: "question-1",
        question: "What identity provider must the product integrate with?",
        reason: "The answer changes authentication and the first integration.",
        impact: "HIGH",
      },
    ],
    implementationPlanProposal: {
      summary: "Deliver the submit-simple-claim slice as one vertical path.",
      tasks: [
        {
          tempId: "task-1",
          title: "Add the claim creation domain model",
          description: "Represent a straightforward claim and its reference.",
          objective: "Give the slice a claim the service can create.",
          verticalSlice: "Submit simple claim",
          workItemId: refs.storyId,
          relatedFeature: "Create claim",
          acceptanceCriteria: ["A claim receives a unique reference when it is created."],
          componentTempIds: ["component-3", "component-4"],
          filesLikely: "Claim domain module",
          guidance: "Model the notice fields the story already requires. Do not generate production code in this plan.",
          validation: "Unit test that a valid notice produces a claim reference.",
          risks: "The mandatory fields may still change.",
          sequence: 1,
          complexity: "SMALL",
          parallelisable: false,
          dependsOn: [],
        },
        {
          tempId: "task-2",
          title: "Implement the claim submission service",
          description: "Create a claim from a valid notice.",
          objective: "Provide the application behaviour behind submission.",
          verticalSlice: "Submit simple claim",
          workItemId: refs.storyId,
          relatedFeature: "Create claim",
          acceptanceCriteria: ["A valid notice is stored and returns a reference."],
          componentTempIds: ["component-3"],
          filesLikely: "Claims service",
          guidance: "Call the domain model. Do not add unrelated claim types.",
          validation: "Unit test for a valid notice and a missing mandatory field.",
          risks: "Validation rules are still thin.",
          sequence: 2,
          complexity: "MEDIUM",
          parallelisable: false,
          dependsOn: ["task-1"],
        },
        {
          tempId: "task-3",
          title: "Expose the claim submission endpoint",
          description: "Accept the notice at the application boundary.",
          objective: "Let the customer screen submit a claim.",
          verticalSlice: "Submit simple claim",
          workItemId: refs.storyId,
          relatedFeature: "Create claim",
          acceptanceCriteria: ["The endpoint returns the claim reference after a valid submission."],
          componentTempIds: ["component-2"],
          filesLikely: "Claims API",
          guidance: "Keep the payload to the fields in the story.",
          validation: "API integration test for success and a rejected notice.",
          risks: "The identity assumption is unresolved.",
          sequence: 3,
          complexity: "MEDIUM",
          parallelisable: false,
          dependsOn: ["task-2"],
        },
        {
          tempId: "task-4",
          title: "Create the claim submission screen",
          description: "A customer can enter the notice and see the reference.",
          objective: "Finish the slice at the customer surface.",
          verticalSlice: "Submit simple claim",
          workItemId: refs.storyId,
          relatedFeature: "Create claim",
          acceptanceCriteria: ["The customer sees a claim reference after submission."],
          componentTempIds: ["component-1"],
          filesLikely: "Customer submission screen",
          guidance: "Connect the screen to the submission endpoint.",
          validation: "Acceptance check against the story criteria.",
          risks: "Accessibility expectations are not fully specified.",
          sequence: 4,
          complexity: "MEDIUM",
          parallelisable: false,
          dependsOn: ["task-3"],
        },
      ],
    },
    technicalReadiness: {
      note: "Identity and retention targets are still open. Ratings in the product are computed, not copied from this note.",
    },
  };
}
