import type { MetricAudience, MetricCategory, MetricDefinition, MetricScope } from "@/modules/analytics/types";

function define(
  key: string,
  name: string,
  category: MetricCategory,
  unit: string,
  calculation: string,
  interpretation: string,
  dataRequirements: string,
  audience: MetricAudience = "both",
  scope: MetricScope = "product",
): MetricDefinition {
  return {
    key,
    name,
    description: calculation,
    category,
    unit,
    calculation,
    interpretation,
    dataRequirements,
    audience,
    scope,
  };
}

const PARTIAL_STAGE =
  "Stage history is not stored. Elapsed time is the gap between recorded milestones, not the time currentStage spent in that stage. Missing either milestone is insufficient data, not zero.";

export const METRIC_DEFINITIONS: MetricDefinition[] = [
  define(
    "idea_to_deployment_lead_time",
    "Idea to deployment",
    "FLOW",
    "duration",
    "Discovery session createdAt, or the product createdAt when no discovery session exists, through the earliest non-demo deployment whose status is SUCCEEDED and completedAt is set.",
    "How long the idea took to reach a recorded successful production deployment. One product contributes one sample.",
    "Both the start timestamp and a successful non-demo deployment completedAt. Demo deployments are excluded.",
    "leadership",
  ),
  define("stage_elapsed_explore", "Explore elapsed", "FLOW", "duration", `Time from discovery start to brief approval or definition start. ${PARTIAL_STAGE}`, "Where calendar time sat in Explore.", "Both milestone timestamps.", "both"),
  define("stage_elapsed_define", "Define elapsed", "FLOW", "duration", `Time from definition creation to definition approval. ${PARTIAL_STAGE}`, "Where calendar time sat in Define.", "Both milestone timestamps.", "both"),
  define("stage_elapsed_build", "Build elapsed", "FLOW", "duration", `Time from architecture start, or definition approval, to coding completion or verification start. ${PARTIAL_STAGE}`, "Where calendar time sat in Build.", "Both milestone timestamps.", "both"),
  define("stage_elapsed_prove", "Prove elapsed", "FLOW", "duration", `Time from verification start to verification approval or a merged pull request. ${PARTIAL_STAGE}`, "Where calendar time sat in Prove.", "Both milestone timestamps.", "both"),
  define("stage_elapsed_ship", "Ship elapsed", "FLOW", "duration", `Time from release-candidate creation to a successful production deployment. ${PARTIAL_STAGE}`, "Where calendar time sat in Ship.", "Both milestone timestamps. Demo candidates are excluded.", "both"),
  define("stage_elapsed_learn", "Learn elapsed", "FLOW", "duration", `Time from a successful production deployment to the next learning decision or real outcome observation. ${PARTIAL_STAGE}`, "Where calendar time sat in Learn.", "Both milestone timestamps.", "both"),
  define("stage_active_explore", "Explore active", "FLOW", "duration", "Sum of agent-run and verification-execution spans that fall inside the Explore elapsed interval.", "Recorded execution inside Explore. This is not inferred human work.", "At least one span with a start and a finish inside the interval. Otherwise not available.", "engineering"),
  define("stage_active_define", "Define active", "FLOW", "duration", "Sum of recorded execution spans inside the Define elapsed interval.", "Recorded execution inside Define.", "A measured span inside the interval. Otherwise not available.", "engineering"),
  define("stage_active_build", "Build active", "FLOW", "duration", "Sum of recorded execution spans inside the Build elapsed interval.", "Recorded execution inside Build.", "A measured span inside the interval. Otherwise not available.", "engineering"),
  define("stage_active_prove", "Prove active", "FLOW", "duration", "Sum of recorded execution spans inside the Prove elapsed interval.", "Recorded execution inside Prove.", "A measured span inside the interval. Otherwise not available.", "engineering"),
  define("stage_active_ship", "Ship active", "FLOW", "duration", "Sum of recorded execution spans inside the Ship elapsed interval.", "Recorded execution inside Ship.", "A measured span inside the interval. Otherwise not available.", "engineering"),
  define("stage_active_learn", "Learn active", "FLOW", "duration", "Sum of recorded execution spans inside the Learn elapsed interval.", "Recorded execution inside Learn.", "A measured span inside the interval. Otherwise not available.", "engineering"),
  define(
    "flow_efficiency",
    "Flow efficiency",
    "FLOW",
    "ratio",
    "Recorded active execution time divided by total elapsed milestone time.",
    "Only shown when every stage that has an elapsed duration also has at least one recorded execution span. Otherwise not available. A higher value is not a target.",
    "Active spans for each elapsed stage. Missing active time is not treated as zero.",
    "leadership",
  ),
  define("approval_wait_brief", "Product Brief approval wait", "FLOW", "duration", "Median of resolved Product Discovery approvals, from requestedAt to resolvedAt.", "How long the brief waited for a person. Pending approvals are listed and are not given a duration of zero.", "A resolved approval with both timestamps.", "both"),
  define("approval_wait_definition", "Definition approval wait", "FLOW", "duration", "Median of resolved Product Definition approvals, from requestedAt to resolvedAt.", "How long the definition waited for a person.", "A resolved approval with both timestamps.", "both"),
  define("approval_wait_architecture", "Architecture approval wait", "FLOW", "duration", "Median of resolved solution-architecture approvals, from requestedAt to resolvedAt.", "How long architecture waited for a person.", "A resolved approval with both timestamps.", "both"),
  define("approval_wait_plan", "Implementation plan approval wait", "FLOW", "duration", "Median of resolved implementation-plan approvals, from requestedAt to resolvedAt.", "How long the plan waited for a person.", "A resolved approval with both timestamps.", "both"),
  define("approval_wait_governance", "Governance approval wait", "FLOW", "duration", "Median of resolved engineering-governance approvals, from requestedAt to resolvedAt.", "How long governance waited for a person.", "A resolved approval with both timestamps.", "both"),
  define("approval_wait_coding_policy", "Coding policy approval wait", "FLOW", "duration", "Median of resolved coding-policy approvals, from requestedAt to resolvedAt.", "How long the coding policy waited for a person.", "A resolved approval with both timestamps.", "both"),
  define("approval_wait_execution_plan", "Execution plan approval wait", "FLOW", "duration", "Would be the wait from an execution-plan request to human approval.", "The coding execution plan does not store a request timestamp and a resolution timestamp, so this wait is not available.", "An approval row with requestedAt and resolvedAt. Activity alone is not enough.", "engineering"),
  define("approval_wait_code_change", "Code review wait", "FLOW", "duration", "Median of resolved code-change approvals, from requestedAt to resolvedAt.", "How long a completed change waited for human code review.", "A resolved CODE_CHANGE approval with both timestamps.", "both"),
  define("approval_wait_verification", "Verification approval wait", "FLOW", "duration", "Median of resolved verification approvals, from requestedAt to resolvedAt.", "How long a verification result waited for a person. This is separate from test execution.", "A resolved VERIFICATION approval with both timestamps.", "both"),
  define("approval_wait_release", "Release approval wait", "FLOW", "duration", "Median of resolved release approvals, from requestedAt to resolvedAt.", "How long a release candidate waited for a person.", "A resolved RELEASE approval with both timestamps. Demo candidates are excluded.", "leadership"),
  define(
    "implementation_cycle_median",
    "Implementation cycle time",
    "DELIVERY",
    "duration",
    "Median from coding-workspace creation to completion for tasks whose status is COMPLETED. Completion is the code-change approval time when that approval exists, otherwise the workspace completedAt, otherwise the task updatedAt.",
    "How long an implementation task took once a workspace existed. Tasks do not store an IN_PROGRESS timestamp, so this is partial.",
    "A completed task and a workspace createdAt. A missing end timestamp drops the sample.",
    "both",
  ),
  define("implementation_cycle_average", "Implementation cycle average", "DELIVERY", "duration", "Average of the same implementation-cycle samples as the median.", "The average can be pulled by one long task. Read it with the median and the sample size.", "Same samples as the implementation median.", "engineering"),
  define("implementation_cycle_p85", "Implementation cycle P85", "DELIVERY", "duration", "85th percentile of implementation-cycle samples.", "Hidden below 20 samples because a small percentile is misleading.", "At least 20 implementation-cycle samples.", "engineering"),
  define("verification_cycle", "Verification cycle time", "DELIVERY", "duration", "Median from verification startedAt to the human verification approval resolvedAt. Demo sessions are excluded.", "The full prove cycle, including time spent waiting for a person.", "startedAt and a resolved verification approval.", "both"),
  define("verification_execution", "Verification execution", "DELIVERY", "duration", "Median of summed verification-command spans (startedAt to completedAt) per non-demo session.", "Testing time, separate from the wait for human approval.", "Command spans with both timestamps. A missing timestamp is not zero.", "engineering"),
  define("pr_cycle", "Pull request cycle time", "DELIVERY", "duration", "Median from pull request createdAt to mergedAt. Demo pull requests are excluded.", "How long a change waited in review and checks before a person merged it.", "A non-demo merged pull request with mergedAt.", "leadership"),
  define("pr_time_to_first_review", "Time to first review", "DELIVERY", "duration", "Median from pull request createdAt to the earliest review submittedAt.", "How long a pull request waited for the first human review.", "A review with submittedAt. Demo pull requests are excluded.", "engineering"),
  define("pr_ci_wait", "CI time", "DELIVERY", "duration", "Median, per pull request, from the earliest check startedAt to the latest check completedAt.", "Measured CI time. Checks without timestamps are excluded rather than treated as instant.", "Every contributing check has startedAt and completedAt.", "engineering"),
  define("pr_changes_requested", "Time in changes requested", "DELIVERY", "duration", "Median from a CHANGES_REQUESTED review submittedAt to the next APPROVED review or the merge.", "How long a pull request stayed in a changes-requested state. Open requests are not given a duration.", "A changes-requested review and a later approval or merge timestamp.", "engineering"),
  define("pr_ready_to_merge", "Ready to merge", "DELIVERY", "duration", "Median from the earliest PULL_REQUEST_READY activity that names the pull request number to mergedAt.", "How long a pull request that the factory had already marked ready waited for a person to merge it.", "A readiness activity whose text contains the pull request number, and mergedAt.", "engineering"),
  define("release_cycle", "Release cycle time", "RELEASE", "duration", "Median from non-demo release-candidate createdAt to the successful production deployment completedAt.", "How long a candidate took to become a recorded successful deployment.", "Candidate createdAt and a successful non-demo deployment completedAt.", "leadership"),
  define("release_to_approval", "Candidate to release approval", "RELEASE", "duration", "Median from release-candidate createdAt to the first approved release approval resolvedAt.", "The human release decision, separate from deployment.", "An approved, non-demo release approval with resolvedAt.", "both"),
  define("release_approval_to_deployment", "Approval to deployment", "RELEASE", "duration", "Median from release approval resolvedAt to deployment startedAt.", "How long a decision waited before deployment began.", "Approval resolvedAt and deployment startedAt.", "both"),
  define("deployment_to_completion", "Deployment duration", "RELEASE", "duration", "Median from deployment startedAt to completedAt for successful production deployments.", "How long the recorded deployment itself took. Post-check time is separate and is not invented when checks have no completedAt.", "startedAt and completedAt on a successful non-demo deployment.", "engineering"),
  define(
    "delivery_predictability",
    "Delivery predictability",
    "DELIVERY",
    "count",
    "Completed work items on an approved product slice, compared with the items on that slice. Items created after the SLICE_APPROVED activity are counted as added. Removals are not inferred.",
    "Whether the approved slice content was finished. This is not velocity. Without an approved slice the result is insufficient commitment data.",
    "A slice in APPROVED, IN_PROGRESS, or COMPLETED. Added-after counts also need a SLICE_APPROVED activity.",
    "leadership",
  ),
  define("scope_change_count", "Scope changes after approval", "DELIVERY", "count", "Count of requirement, architecture, implementation, and release changes recorded after the relevant approval.", "When approved scope moved. Each event names the downstream rework that started afterwards.", "A recorded review-required flag, a stale contract, a stale release approval, or a proposal created after approval.", "both"),
  define("rework_rate_tasks", "Task rework rate", "QUALITY", "ratio", "Implementation tasks with a coding revision after human review or pull-request review, divided by implementation tasks that had a workspace.", "Share of executed tasks that needed a revision after review. A revision before any review is not counted.", "At least one executed task. Numerator and denominator are both shown.", "both"),
  define("rework_rate_pull_requests", "Pull request rework rate", "QUALITY", "ratio", "Non-demo pull requests with a CHANGES_REQUESTED review, divided by non-demo pull requests created.", "Share of pull requests that came back for code changes.", "At least one non-demo pull request.", "engineering"),
  define("rework_rate_verification", "Verification repeat rate", "QUALITY", "ratio", "Non-demo tasks verified again after a stale session or a new commit, divided by tasks that have a non-demo verification session.", "Repeat verification caused by an implementation change. An extra session without that evidence is not rework.", "At least one non-demo verification session.", "engineering"),
  define("defects_found_in_verification", "Defects found in verification", "QUALITY", "count", "Defect work items linked from a verification session.", "Defects the factory traced to verification.", "Verification defect links. Unlinked defects are not added to this count.", "both"),
  define("defects_found_after_deployment", "Defects found after deployment", "QUALITY", "count", "Release issues on non-demo release candidates.", "Issues recorded after a candidate existed. Low severity is still an issue and does not by itself fail the deployment.", "Release issue rows. Zero is a real count when a production deployment exists. With no production deployment the count is insufficient.", "both"),
  define("defects_open_critical_high", "Open critical and high defects", "QUALITY", "count", "Open defect work items at CRITICAL or HIGH priority, plus open release issues at HIGH or CRITICAL.", "What still needs attention. Low and medium issues are excluded from this count.", "Current open records. This is a snapshot, not a windowed rate.", "leadership"),
  define("open_defect_age", "Open defect age", "QUALITY", "duration", "Median age of open defect work items, from createdAt to the calculation time.", "How long known defects have stayed open.", "At least one open defect. Done defects are excluded.", "engineering"),
  define(
    "defect_escape_rate",
    "Defect escape rate",
    "QUALITY",
    "ratio",
    "Post-deployment release issues linked to a successfully deployed non-demo candidate, divided by those issues plus verification defects on the released tasks.",
    "Of the defects the factory can trace to released scope, how many were found after deployment. Low-severity issues stay in the numerator as escapes, not as failed changes.",
    "A successful production deployment and traceable defects on that scope. Zero divided by zero is insufficient.",
    "leadership",
  ),
  define("acceptance_verified", "Acceptance criteria verified", "QUALITY", "count", "Verification coverage rows whose status is VERIFIED, excluding demo sessions.", "Criteria a verification session marked verified.", "Coverage rows. No coverage rows is insufficient, not a pass rate of zero.", "engineering"),
  define("acceptance_failed", "Acceptance criteria failed", "QUALITY", "count", "Verification coverage rows whose status is FAILED, excluding demo sessions.", "Criteria a verification session marked failed.", "Coverage rows.", "engineering"),
  define("acceptance_manual", "Acceptance criteria checked manually", "QUALITY", "count", "Verification coverage rows a person confirmed.", "Criteria that needed a person to confirm the result.", "Coverage rows with humanConfirmed.", "engineering"),
  define("regression_failures", "Regression failures", "QUALITY", "count", "Verification executions whose kind is EXISTING_REGRESSION and whose status is FAILED.", "Existing tests that failed while verifying a change.", "Regression executions. No regression execution is insufficient, not a claim of zero failures.", "engineering"),
  define("reverification_rate", "Re-verification rate", "QUALITY", "ratio", "Same numerator and denominator as the verification repeat rate.", "How often verification had to run again because the implementation changed.", "Same evidence as the verification repeat rate.", "both"),
  define("agent_runs", "Agent runs", "AI", "count", "Agent runs whose completion or creation falls in the window, counted by status.", "How often agents ran, and how those runs finished. This is not a productivity score.", "AgentRun rows.", "leadership"),
  define("ai_execution_time", "Agent execution time", "AI", "duration", "Sum of AgentRun duration values, which are stored in milliseconds.", "Time the agents actually ran. This is not hours saved.", "Runs with a duration. Missing durations are omitted, not treated as zero.", "leadership"),
  define("human_approval_time", "Human approval time", "AI", "duration", "Sum of resolved approval waits in the window.", "Time people spent waiting at gates, shown beside agent execution. The two numbers are not subtracted.", "Resolved approvals with both timestamps.", "leadership"),
  define(
    "automation_rate",
    "Automated execution rate",
    "AI",
    "ratio",
    "Eligible low-risk coding tasks completed in AUTONOMOUS mode, divided by eligible low-risk coding tasks that were executed. Supervised and human-only counts are shown beside the rate.",
    "How often low-risk work ran without a person in the loop. A higher rate is not a target.",
    "A coding contract whose effective risk is LOW and a workspace. An override replaces the original mode.",
    "leadership",
  ),
  define("first_pass_coding", "Coding first pass", "AI", "ratio", "Completed coding runs whose workspace has no coding revision and did not escalate, divided by completed coding runs.", "The coding agent finished without a later revision. It is not combined with other agents.", "A completed CODING run that can be tied to a workspace.", "leadership"),
  define("first_pass_verification", "Verification first pass", "AI", "ratio", "Tasks whose only non-demo verification session completed without a later session, divided by tasks with a completed non-demo session.", "The verification agent reached a result without a repeat. It is not combined with coding first pass.", "A non-demo session with a verdict.", "leadership"),
  define("first_pass_architecture", "Architecture first pass", "AI", "ratio", "Cases with exactly one architecture proposal and that proposal committed, divided by cases with at least one architecture proposal.", "The architecture proposal was accepted without a regeneration.", "Architecture proposal rows.", "engineering"),
  define("first_pass_requirements", "Requirements first pass", "AI", "ratio", "Cases with exactly one definition proposal and that proposal committed, divided by cases with at least one definition proposal.", "The requirements proposal was accepted without a regeneration.", "Definition proposal rows.", "engineering"),
  define("escalation_count", "Escalations", "AI", "count", "Coding and verification escalations in the window, grouped by category.", "Where an agent stopped and asked a person. The category is the recorded escalation type.", "Escalation rows.", "leadership"),
  define("escalation_resolution", "Escalation resolution time", "AI", "duration", "Median from escalation createdAt to resolvedAt.", "How long an escalation stayed open. Unresolved escalations are listed without a duration.", "resolvedAt on the escalation.", "engineering"),
  define("human_intervention_count", "Human interventions", "AI", "count", "Recorded edits, risk overrides, code-change requests, manual verification, pull-request change requests, accepted risks, answered release questions, and manually recorded deployments.", "Where people steered the factory. A higher count is a control signal, not a failure.", "Activity rows and the matching operational records.", "leadership"),
  define("token_usage", "Token usage", "AI", "count", "Sum of input and output token counts stored on agent-run output.", "Provider usage when the provider returned it.", "Numeric token fields on the run output. Missing fields are not guessed.", "engineering"),
  define("agent_cost", "Agent cost", "AI", "currency", "Sum of AgentRun estimatedCost.", "Shown only when a cost was stored. Otherwise cost is not available.", "A non-null estimatedCost. The factory does not invent a price.", "engineering"),
  define("governance_findings", "Governance findings", "GOVERNANCE", "count", "Governance findings in the window, grouped by severity.", "What the governance review recorded. Severity comes from the finding, not from a narrative.", "Governance finding rows.", "both"),
  define("findings_resolved_before_coding", "Findings resolved before coding", "GOVERNANCE", "count", "Findings that are not open and were last updated before the first coding workspace, or before any workspace exists.", "Findings closed before implementation started.", "Finding status and the first workspace createdAt.", "engineering"),
  define("risks_accepted", "Risks accepted", "GOVERNANCE", "count", "Governance findings with status RISK_ACCEPTED, plus release risk factors a person accepted.", "Risks a person explicitly accepted. Acceptance is not treated as resolution by the model.", "Finding status or a release risk acceptance.", "leadership"),
  define("coding_risk_distribution", "Coding risk distribution", "GOVERNANCE", "count", "Coding risk assessments grouped by the effective risk after any human override.", "How implementation tasks were classified before coding.", "Coding risk assessment rows.", "engineering"),
  define("governance_cycle", "Governance review cycle", "GOVERNANCE", "duration", "Median engineering-governance approval wait.", "How long the governance gate took once it was requested.", "A resolved ENGINEERING_GOVERNANCE approval.", "both"),
  define("governance_rereview_rate", "Governance re-review rate", "GOVERNANCE", "ratio", "Governance reviews that are a later version or are flagged review-required, divided by governance reviews.", "How often governance had to be looked at again.", "At least one governance review.", "engineering"),
  define("policy_overrides", "Policy overrides", "GOVERNANCE", "count", "Coding risk rows with an override timestamp.", "Times a person changed the recommended coding risk or execution mode.", "overriddenAt on a coding risk assessment.", "engineering"),
  define("release_candidates", "Release candidates", "RELEASE", "count", "Non-demo release candidates created in the window.", "Candidates a person created. Demo candidates are excluded from this count and labelled on the timeline.", "Release candidate rows with demo false.", "leadership"),
  define("approved_releases", "Approved releases", "RELEASE", "count", "Non-demo candidates with an approved release approval that is not stale.", "Releases a person approved on the current evidence.", "A RELEASE approval with status APPROVED and stale false.", "leadership"),
  define("successful_deployments", "Successful deployments", "RELEASE", "count", "Non-demo deployments in a non-demo environment whose status is SUCCEEDED.", "Deployments a person recorded as successful.", "Deployment records. Demo records are excluded.", "leadership"),
  define("failed_deployments", "Failed deployments", "RELEASE", "count", "Non-demo production deployments whose status is FAILED.", "Deployments a person recorded as failed. A later rollback is counted separately.", "Deployment status FAILED.", "leadership"),
  define("rollbacks", "Rollbacks", "RELEASE", "count", "Non-demo production deployments whose status is ROLLED_BACK.", "Rollbacks a person recorded. The original deployment row is kept.", "Deployment status ROLLED_BACK.", "leadership"),
  define("deployment_frequency_7d", "Deployment frequency, 7 days", "RELEASE", "count", "Successful production deployments whose completedAt is in the last 7 days.", "How often production changed this week. The window is fixed, not the page filter.", "Deployment completedAt. Demo records are excluded.", "leadership"),
  define("deployment_frequency_30d", "Deployment frequency, 30 days", "RELEASE", "count", "Successful production deployments whose completedAt is in the last 30 days.", "How often production changed this month.", "Deployment completedAt. Demo records are excluded.", "leadership"),
  define("deployment_frequency_90d", "Deployment frequency, 90 days", "RELEASE", "count", "Successful production deployments whose completedAt is in the last 90 days.", "How often production changed this quarter.", "Deployment completedAt. Demo records are excluded.", "leadership"),
  define(
    "change_failure_rate",
    "Change failure rate",
    "RELEASE",
    "ratio",
    "Production deployments that failed, were rolled back, or have a linked HIGH or CRITICAL release issue, divided by all production deployments.",
    "A DORA-style change failure rate. A low or medium issue does not mark the deployment as failed.",
    "At least one non-demo production deployment. Zero deployments is insufficient, not 0%.",
    "leadership",
  ),
  define(
    "lead_time_for_changes",
    "Lead time for changes",
    "RELEASE",
    "duration",
    "Earliest coding workspace createdAt for the tasks on a release, through that release's successful production deployment completedAt. Commit author time is not stored, so the workspace clock is the definition.",
    "How long released work took from the start of coding to production. This is not the idea-to-deployment lead time.",
    "A workspace for a released task and a successful production deployment completedAt.",
    "leadership",
  ),
  define(
    "mttr",
    "Time to restore",
    "RELEASE",
    "duration",
    "From a failed deployment, a rollback, or an open critical release issue to a later successful deployment or the issue resolvedAt.",
    "Shown only when both the failure and the restoration are recorded. Otherwise insufficient.",
    "A failure event and a later restoration event.",
    "leadership",
  ),
  define("outcomes_achieved", "Outcomes achieved", "OUTCOME", "count", "Product outcomes whose status is ACHIEVED.", "Outcomes a person marked achieved. An observation does not do this.", "Outcome status.", "leadership"),
  define("outcomes_awaiting_evidence", "Outcomes awaiting evidence", "OUTCOME", "count", "Outcomes that are not achieved and have no non-demo observation.", "Outcomes that still need a real measurement. Demo observations do not count.", "Outcome status and observation rows.", "leadership"),
  define(
    "delivery_complete_outcome_pending",
    "Delivery complete, outcome pending",
    "OUTCOME",
    "count",
    "Outcomes that are not ACHIEVED while the product has a successful non-demo deployment.",
    "The software is in production and the outcome is still open. That means learning is still required. It is not an automatic failure.",
    "A successful production deployment and an outcome that is not achieved.",
    "leadership",
  ),
  define("products_blocked", "Products blocked", "PORTFOLIO", "count", "Products with a blocked work item, an open high or critical release issue, or a governance review that is flagged for another look.", "Where a product cannot move cleanly.", "Those operational records.", "leadership", "portfolio"),
  define("products_ready_for_action", "Products ready for a person", "PORTFOLIO", "count", "Products with at least one pending approval.", "Where a person is the next step.", "Approval rows with status PENDING.", "leadership", "portfolio"),
  define("portfolio_products", "Products in view", "PORTFOLIO", "count", "Products included in the portfolio calculation.", "The sample behind every portfolio aggregate.", "Product rows.", "leadership", "portfolio"),
];

const BY_KEY = new Map(METRIC_DEFINITIONS.map((definition) => [definition.key, definition]));

export function getMetricDefinition(key: string) {
  return BY_KEY.get(key) ?? null;
}

export function definitionsFor(scope: "product" | "portfolio") {
  return METRIC_DEFINITIONS.filter((definition) => definition.scope === scope || definition.scope === "both");
}
